fixtures:
  repositories:
    apt:
      repo: 'https://github.com/puppetlabs/puppetlabs-apt.git'
      ref: '2.1.1'
    concat:
      repo: 'https://github.com/puppetlabs/puppetlabs-concat.git'
      ref: '1.2.4'
    git:
      repo: 'https://github.com/puppetlabs/puppetlabs-git.git'
      ref: '0.4.0'
    nodejs:
      repo: 'https://github.com/puppetlabs/puppetlabs-nodejs.git'
      ref: '0.7.1'
    python:
      repo: 'https://github.com/stankevich/puppet-python.git'
      ref: '1.9.7'
    stdlib:
      repo: 'https://github.com/puppetlabs/puppetlabs-stdlib.git'
      ref: '4.8.0'
    supervisord:
      repo: 'https://github.com/ajcrowe/puppet-supervisord.git'
      ref: 'v0.5.2'
  symlinks:
    sentry: "#{source_dir}"
